
[package]
name = "phantom-ml-core"
version = "1.0.1"
description = "Enterprise machine learning services for threat detection and security analytics"
edition = "2021"
license = "MIT"
authors = ["Phantom Spire Security Team"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
futures = "0.3"
regex = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"

# Machine Learning Dependencies
ndarray = { version = "0.15", features = ["rayon", "serde"] }
ndarray-linalg = { version = "0.16", features = ["netlib"] }
ndarray-rand = "0.14"
linfa = "0.7"
linfa-trees = "0.7"
linfa-linear = "0.7"
linfa-clustering = "0.7"
linfa-nn = "0.7"
linfa-preprocessing = "0.7"
linfa-reduction = "0.7"
# linfa-ensemble = "0.7" # This crate doesn't exist
candle-core = "0.6"
candle-nn = "0.6"
candle-datasets = "0.6"
candle-transformers = "0.6"
tch = { version = "0.16", optional = true }
polars = { version = "0.39", features = ["lazy", "temporal", "strings", "csv", "json"] }
smartcore = { version = "0.3", features = ["serde"] }
statrs = "0.17"

# Serialization and Persistence
bincode = "1.3"
rmp-serde = "1.1"
memmap2 = "0.9"

# Performance and Parallelization
rayon = "1.8"
crossbeam = "0.8"

# Plugin system dependencies
libloading = "0.8"
wasmtime = "25.0.0"
wasmtime-wasi = "25.0.0"
thiserror = "1.0"
anyhow = "1.0"
dashmap = "6.0"
notify = "6.0"
semver = "1.0"
sha2 = "0.10"
toml = "0.8"
async-trait = "0.1"
parking_lot = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"
reqwest = { version = "0.11", features = ["json", "stream"] }
tempfile = "3.8"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
