version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: phantom-spire-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:phantom_secure_pass@mongo:27017/phantom-spire
      - REDIS_URL=redis://:phantom_redis_pass@redis:6379
      - POSTGRESQL_URI=postgresql://postgres:phantom_secure_pass@postgres:5432/phantom_spire
      - MYSQL_URI=mysql://phantom_user:phantom_secure_pass@mysql:3306/phantom_spire
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - WAIT_FOR_DB=true
      - RUN_MIGRATIONS=true
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./setup:/app/setup
      - app_data:/app/data
    networks:
      - phantom-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: phantom-spire-dev
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:phantom_secure_pass@mongo:27017/phantom-spire-dev
      - REDIS_URL=redis://:phantom_redis_pass@redis:6379/1
      - POSTGRESQL_URI=postgresql://postgres:phantom_secure_pass@postgres:5432/phantom_spire_dev
      - MYSQL_URI=mysql://phantom_user:phantom_secure_pass@mysql:3306/phantom_spire_dev
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - .:/app
      - node_modules_dev:/app/node_modules
      - ./logs:/app/logs
    networks:
      - phantom-network
    profiles:
      - development

  mongo:
    image: mongo:7
    container_name: phantom-spire-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_DATABASE: phantom-spire
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: phantom_secure_pass
    networks:
      - phantom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - phantom-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: phantom_spire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: phantom_secure_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    networks:
      - phantom-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_DATABASE: phantom_spire
      MYSQL_USER: phantom_user
      MYSQL_PASSWORD: phantom_secure_pass
      MYSQL_ROOT_PASSWORD: phantom_root_pass
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    networks:
      - phantom-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/config:/usr/share/elasticsearch/config:ro
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=phantom_elastic_pass
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - phantom-network

  # Database Administration Tools
  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mysql
      - mongo
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
    networks:
      - phantom-network

  # MongoDB Administration
  mongo-express:
    image: mongo-express:1.0.0
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: phantom_secure_pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:phantom_secure_pass@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: phantom_admin
    networks:
      - phantom-network

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: local:redis:6379:0:phantom_redis_pass
      HTTP_USER: admin
      HTTP_PASSWORD: phantom_admin
      PORT: 8081
    networks:
      - phantom-network

  # Elasticsearch Management
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=phantom_elastic_pass
    networks:
      - phantom-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local
  mysql_data:
    driver: local
  elasticsearch_data:
    driver: local
  app_data:
    driver: local
  node_modules_dev:
    driver: local

networks:
  phantom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16