import { Router } from 'express';
import initialaccessanalyzerRoutes from './tactics-analysis/initialaccessanalyzerRoutes';
import executiontacticsmapperRoutes from './tactics-analysis/executiontacticsmapperRoutes';
import persistencetrackerRoutes from './tactics-analysis/persistencetrackerRoutes';
import privilegeescalationdetectorRoutes from './tactics-analysis/privilegeescalationdetectorRoutes';
import defenseevasionanalyzerRoutes from './tactics-analysis/defenseevasionanalyzerRoutes';
import credentialaccessmonitorRoutes from './tactics-analysis/credentialaccessmonitorRoutes';
import discoveryplatformRoutes from './tactics-analysis/discoveryplatformRoutes';
import lateralmovementtrackerRoutes from './tactics-analysis/lateralmovementtrackerRoutes';
import collectionanalyzerRoutes from './tactics-analysis/collectionanalyzerRoutes';
import exfiltrationdetectorRoutes from './tactics-analysis/exfiltrationdetectorRoutes';
import commandcontrolanalyzerRoutes from './tactics-analysis/commandcontrolanalyzerRoutes';
import impactassessmentengineRoutes from './tactics-analysis/impactassessmentengineRoutes';
import attacktechniquemapperRoutes from './techniques-mapping/attacktechniquemapperRoutes';
import subtechniqueanalyzerRoutes from './techniques-mapping/subtechniqueanalyzerRoutes';
import techniqueevolutiontrackerRoutes from './techniques-mapping/techniqueevolutiontrackerRoutes';
import mitreattackintegratorRoutes from './techniques-mapping/mitreattackintegratorRoutes';
import techniquecoverageanalyzerRoutes from './techniques-mapping/techniquecoverageanalyzerRoutes';
import techniquecorrelationengineRoutes from './techniques-mapping/techniquecorrelationengineRoutes';
import techniquevalidationsystemRoutes from './techniques-mapping/techniquevalidationsystemRoutes';
import techniqueprioritizationengineRoutes from './techniques-mapping/techniqueprioritizationengineRoutes';
import proceduredocumentationcenterRoutes from './procedures-intelligence/proceduredocumentationcenterRoutes';
import procedureevolutiontrackerRoutes from './procedures-intelligence/procedureevolutiontrackerRoutes';
import procedurestandardizationhubRoutes from './procedures-intelligence/procedurestandardizationhubRoutes';
import procedurevalidationengineRoutes from './procedures-intelligence/procedurevalidationengineRoutes';
import procedureautomationworkflowRoutes from './procedures-intelligence/procedureautomationworkflowRoutes';
import procedurecompliancemonitorRoutes from './procedures-intelligence/procedurecompliancemonitorRoutes';
import procedureeffectivenessanalyzerRoutes from './procedures-intelligence/procedureeffectivenessanalyzerRoutes';
import procedureoptimizationengineRoutes from './procedures-intelligence/procedureoptimizationengineRoutes';
import actorttpprofilerRoutes from './threat-actor-ttp/actorttpprofilerRoutes';
import ttpattributionengineRoutes from './threat-actor-ttp/ttpattributionengineRoutes';
import actorbehavioranalyzerRoutes from './threat-actor-ttp/actorbehavioranalyzerRoutes';
import ttpsignaturegeneratorRoutes from './threat-actor-ttp/ttpsignaturegeneratorRoutes';
import actorttpevolutionRoutes from './threat-actor-ttp/actorttpevolutionRoutes';
import ttpintelligencehubRoutes from './threat-actor-ttp/ttpintelligencehubRoutes';
import actorttpcorrelationRoutes from './threat-actor-ttp/actorttpcorrelationRoutes';
import ttpthreatscoringRoutes from './threat-actor-ttp/ttpthreatscoringRoutes';
import ttptrendanalyzerRoutes from './ttp-analytics/ttptrendanalyzerRoutes';
import ttppatternrecognitionRoutes from './ttp-analytics/ttppatternrecognitionRoutes';
import ttppredictivemodelingRoutes from './ttp-analytics/ttppredictivemodelingRoutes';
import ttpriskassessmentRoutes from './ttp-analytics/ttpriskassessmentRoutes';
import ttpimpactanalyzerRoutes from './ttp-analytics/ttpimpactanalyzerRoutes';
import ttpfrequencytrackerRoutes from './ttp-analytics/ttpfrequencytrackerRoutes';
import ttpeffectivenessmetricsRoutes from './ttp-analytics/ttpeffectivenessmetricsRoutes';
import ttpbenchmarkingengineRoutes from './ttp-analytics/ttpbenchmarkingengineRoutes';
import ttpperformanceanalyticsRoutes from './ttp-analytics/ttpperformanceanalyticsRoutes';

const router = Router();

// TTP Route Integrations
router.use('/tactics-analysis/initialaccessanalyzer', initialaccessanalyzerRoutes);
router.use('/tactics-analysis/executiontacticsmapper', executiontacticsmapperRoutes);
router.use('/tactics-analysis/persistencetracker', persistencetrackerRoutes);
router.use('/tactics-analysis/privilegeescalationdetector', privilegeescalationdetectorRoutes);
router.use('/tactics-analysis/defenseevasionanalyzer', defenseevasionanalyzerRoutes);
router.use('/tactics-analysis/credentialaccessmonitor', credentialaccessmonitorRoutes);
router.use('/tactics-analysis/discoveryplatform', discoveryplatformRoutes);
router.use('/tactics-analysis/lateralmovementtracker', lateralmovementtrackerRoutes);
router.use('/tactics-analysis/collectionanalyzer', collectionanalyzerRoutes);
router.use('/tactics-analysis/exfiltrationdetector', exfiltrationdetectorRoutes);
router.use('/tactics-analysis/commandcontrolanalyzer', commandcontrolanalyzerRoutes);
router.use('/tactics-analysis/impactassessmentengine', impactassessmentengineRoutes);
router.use('/techniques-mapping/attacktechniquemapper', attacktechniquemapperRoutes);
router.use('/techniques-mapping/subtechniqueanalyzer', subtechniqueanalyzerRoutes);
router.use('/techniques-mapping/techniqueevolutiontracker', techniqueevolutiontrackerRoutes);
router.use('/techniques-mapping/mitreattackintegrator', mitreattackintegratorRoutes);
router.use('/techniques-mapping/techniquecoverageanalyzer', techniquecoverageanalyzerRoutes);
router.use('/techniques-mapping/techniquecorrelationengine', techniquecorrelationengineRoutes);
router.use('/techniques-mapping/techniquevalidationsystem', techniquevalidationsystemRoutes);
router.use('/techniques-mapping/techniqueprioritizationengine', techniqueprioritizationengineRoutes);
router.use('/procedures-intelligence/proceduredocumentationcenter', proceduredocumentationcenterRoutes);
router.use('/procedures-intelligence/procedureevolutiontracker', procedureevolutiontrackerRoutes);
router.use('/procedures-intelligence/procedurestandardizationhub', procedurestandardizationhubRoutes);
router.use('/procedures-intelligence/procedurevalidationengine', procedurevalidationengineRoutes);
router.use('/procedures-intelligence/procedureautomationworkflow', procedureautomationworkflowRoutes);
router.use('/procedures-intelligence/procedurecompliancemonitor', procedurecompliancemonitorRoutes);
router.use('/procedures-intelligence/procedureeffectivenessanalyzer', procedureeffectivenessanalyzerRoutes);
router.use('/procedures-intelligence/procedureoptimizationengine', procedureoptimizationengineRoutes);
router.use('/threat-actor-ttp/actorttpprofiler', actorttpprofilerRoutes);
router.use('/threat-actor-ttp/ttpattributionengine', ttpattributionengineRoutes);
router.use('/threat-actor-ttp/actorbehavioranalyzer', actorbehavioranalyzerRoutes);
router.use('/threat-actor-ttp/ttpsignaturegenerator', ttpsignaturegeneratorRoutes);
router.use('/threat-actor-ttp/actorttpevolution', actorttpevolutionRoutes);
router.use('/threat-actor-ttp/ttpintelligencehub', ttpintelligencehubRoutes);
router.use('/threat-actor-ttp/actorttpcorrelation', actorttpcorrelationRoutes);
router.use('/threat-actor-ttp/ttpthreatscoring', ttpthreatscoringRoutes);
router.use('/ttp-analytics/ttptrendanalyzer', ttptrendanalyzerRoutes);
router.use('/ttp-analytics/ttppatternrecognition', ttppatternrecognitionRoutes);
router.use('/ttp-analytics/ttppredictivemodeling', ttppredictivemodelingRoutes);
router.use('/ttp-analytics/ttpriskassessment', ttpriskassessmentRoutes);
router.use('/ttp-analytics/ttpimpactanalyzer', ttpimpactanalyzerRoutes);
router.use('/ttp-analytics/ttpfrequencytracker', ttpfrequencytrackerRoutes);
router.use('/ttp-analytics/ttpeffectivenessmetrics', ttpeffectivenessmetricsRoutes);
router.use('/ttp-analytics/ttpbenchmarkingengine', ttpbenchmarkingengineRoutes);
router.use('/ttp-analytics/ttpperformanceanalytics', ttpperformanceanalyticsRoutes);

export default router;