[env]
LIB = { value = "C:\\Users\\justi\\AppData\\Local\\node-gyp\\Cache\\22.19.0\\x64", force = true }
NODE_LIB_FILE = { value = "C:\\Users\\justi\\AppData\\Local\\node-gyp\\Cache\\22.19.0\\x64\\node.lib", force = true }
