[package]
name = "phantom-ioc-core"
version = "0.1.0"
description = "IOC processing core with threat intelligence"
edition = "2021"

[lib]
name = "phantom_ioc_core"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
uuid = { version = "1.0", features = ["v4", "serde", "js"] }
regex = "1.10"
thiserror = "1.0"

# WASI-specific dependencies
wasm-bindgen = { version = "0.2", features = ["std"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
console_error_panic_hook = "0.1"
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3", features = ["console"] }
