[package]
name = "phantom-intel-core"
version = "1.0.1"
edition = "2021"
description = "Advanced Threat Intelligence engine for comprehensive intelligence gathering, analysis, and correlation"
license = "MIT"
authors = ["Phantom Spire Security"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.3.0", default-features = false, features = ["napi6", "serde-json", "tokio_rt"], optional = true }
napi-derive = { version = "3.2.5", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"
thiserror = "2.0.16"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
num_cpus = "1.16"
futures-util = "0.3"
log = "0.4"
futures = "0.3"
bincode = "1.3"

# High-performance threat intelligence processing
reqwest = { version = "0.12.23", features = ["json", "rustls-tls"], default-features = false }
base64 = "0.21"
sha2 = "0.10"
indexmap = { version = "2.0", features = ["serde"] }
url = "2.0"
ipnetwork = "0.20"
cidr = "0.2"
maxminddb = "0.23"
trust-dns-resolver = "0.23"
whois-rust = "1.6"
simd-json = "0.13"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
once_cell = "1.19"

# Web frameworks (optional)
actix-web = { version = "4.4", optional = true }
rocket = { version = "0.5", features = ["json"], optional = true }

# Database dependencies (optional)
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-chrono-0_4"], optional = true }
elasticsearch = { version = "8.15.0-alpha.1", optional = true }
mongodb = { version = "3.3.0", optional = true }
deadpool-postgres = { version = "0.14.1", optional = true }
redis = { version = "0.32.5", features = ["aio", "tokio-comp", "connection-manager"] }

# ORM (optional)
diesel = { version = "2.1", features = ["postgres", "mysql", "sqlite", "r2d2", "chrono", "uuid"], optional = true }
diesel_migrations = { version = "2.1", optional = true }

# Message queues and streaming (optional)
rdkafka = { version = "0.38.0", features = ["cmake-build"], optional = true }
lapin = { version = "3.4.0", optional = true }

# Monitoring and observability (optional)
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }
prometheus = { version = "0.14.0", optional = true }
metrics = { version = "0.24.2", optional = true }

# Security and cryptography (optional)
ring = { version = "0.17", optional = true }
rustls = { version = "0.23.31", optional = true }
jsonwebtoken = { version = "9.2", optional = true }

# Configuration management (optional)
config = { version = "0.15.15", features = ["yaml", "json"], optional = true }

# Rate limiting (optional)
governor = { version = "0.10.1", optional = true }

[features]
default = ["local"]

# Core features
napi = ["dep:napi", "dep:napi-derive"]
local = []

# Database backends
postgres = ["tokio-postgres", "deadpool-postgres", "sqlx", "diesel"]
redis-store = ["redis"]
mongodb-store = ["mongodb"]
elasticsearch-store = ["elasticsearch"]
all-databases = ["postgres", "redis-store", "mongodb-store", "elasticsearch-store"]

# Web and messaging
web-full = ["actix-web", "reqwest"]
messaging = ["redis-store"]  # Using Redis for pub/sub messaging
caching = ["redis-store"]    # Redis-based caching layer

# Enterprise monitoring and security
monitoring = ["tracing", "tracing-subscriber", "prometheus", "metrics"]
crypto = ["ring", "rustls", "jsonwebtoken", "sha2", "base64"]
compression = ["flate2"]
diesel-orm = ["diesel", "diesel_migrations"]
advanced-config = []

# Bundled feature sets
enterprise = ["all-databases", "messaging", "caching", "monitoring", "crypto"]
full = ["enterprise", "web-full", "diesel-orm", "compression", "advanced-config"]
[build-dependencies]
napi-build = "2.1.0"
