import { Router } from 'express';
import { userDirectoryPortalRoutes } from './userDirectoryPortalRoutes.js';
import { userLifecycleManagerRoutes } from './userLifecycleManagerRoutes.js';
import { userProfileDashboardRoutes } from './userProfileDashboardRoutes.js';
import { userSettingsCenterRoutes } from './userSettingsCenterRoutes.js';
import { userAccountManagerRoutes } from './userAccountManagerRoutes.js';
import { userGroupCoordinatorRoutes } from './userGroupCoordinatorRoutes.js';
import { userDelegationSystemRoutes } from './userDelegationSystemRoutes.js';
import { userBulkOperationsRoutes } from './userBulkOperationsRoutes.js';
import { userSynchronizationHubRoutes } from './userSynchronizationHubRoutes.js';
import { userAdminConsoleRoutes } from './userAdminConsoleRoutes.js';
import { roleDefinitionStudioRoutes } from './roleDefinitionStudioRoutes.js';
import { permissionMatrixManagerRoutes } from './permissionMatrixManagerRoutes.js';
import { roleHierarchyBuilderRoutes } from './roleHierarchyBuilderRoutes.js';
import { accessControlDashboardRoutes } from './accessControlDashboardRoutes.js';
import { roleAssignmentCenterRoutes } from './roleAssignmentCenterRoutes.js';
import { permissionAuditSystemRoutes } from './permissionAuditSystemRoutes.js';
import { roleTemplateLibraryRoutes } from './roleTemplateLibraryRoutes.js';
import { accessReviewManagerRoutes } from './accessReviewManagerRoutes.js';
import { privilegeEscalationControlRoutes } from './privilegeEscalationControlRoutes.js';
import { roleAnalyticsInsightsRoutes } from './roleAnalyticsInsightsRoutes.js';
import { organizationBuilderRoutes } from './organizationBuilderRoutes.js';
import { departmentManagementHubRoutes } from './departmentManagementHubRoutes.js';
import { teamFormationStudioRoutes } from './teamFormationStudioRoutes.js';
import { organizationalChartManagerRoutes } from './organizationalChartManagerRoutes.js';
import { reportingStructureDesignerRoutes } from './reportingStructureDesignerRoutes.js';
import { crossFunctionalTeamCoordinatorRoutes } from './crossFunctionalTeamCoordinatorRoutes.js';
import { organizationalChangeManagerRoutes } from './organizationalChangeManagerRoutes.js';
import { locationBranchManagerRoutes } from './locationBranchManagerRoutes.js';
import { costCenterAllocationRoutes } from './costCenterAllocationRoutes.js';
import { organizationalAnalyticsRoutes } from './organizationalAnalyticsRoutes.js';
import { userOnboardingJourneyRoutes } from './userOnboardingJourneyRoutes.js';
import { userEngagementDashboardRoutes } from './userEngagementDashboardRoutes.js';
import { userFeedbackCenterRoutes } from './userFeedbackCenterRoutes.js';
import { userTrainingAcademyRoutes } from './userTrainingAcademyRoutes.js';
import { userSupportPortalRoutes } from './userSupportPortalRoutes.js';
import { userCommunicationHubRoutes } from './userCommunicationHubRoutes.js';
import { userCollaborationSpacesRoutes } from './userCollaborationSpacesRoutes.js';
import { userProductivityInsightsRoutes } from './userProductivityInsightsRoutes.js';
import { userWellnessDashboardRoutes } from './userWellnessDashboardRoutes.js';
import { userRecognitionSystemRoutes } from './userRecognitionSystemRoutes.js';
import { userSecurityDashboardRoutes } from './userSecurityDashboardRoutes.js';
import { userAuthenticationManagerRoutes } from './userAuthenticationManagerRoutes.js';
import { userSessionMonitorRoutes } from './userSessionMonitorRoutes.js';
import { userPrivacyControlCenterRoutes } from './userPrivacyControlCenterRoutes.js';
import { userAccessLogsRoutes } from './userAccessLogsRoutes.js';
import { userComplianceTrackerRoutes } from './userComplianceTrackerRoutes.js';
import { userRiskAssessmentRoutes } from './userRiskAssessmentRoutes.js';
import { userDeviceManagementRoutes } from './userDeviceManagementRoutes.js';
import { userDataGovernanceRoutes } from './userDataGovernanceRoutes.js';

const router = Router();

// Register all user management routes
router.use('/user-directory-portal', userDirectoryPortalRoutes);
  router.use('/user-lifecycle-manager', userLifecycleManagerRoutes);
  router.use('/user-profile-dashboard', userProfileDashboardRoutes);
  router.use('/user-settings-center', userSettingsCenterRoutes);
  router.use('/user-account-manager', userAccountManagerRoutes);
  router.use('/user-group-coordinator', userGroupCoordinatorRoutes);
  router.use('/user-delegation-system', userDelegationSystemRoutes);
  router.use('/user-bulk-operations', userBulkOperationsRoutes);
  router.use('/user-synchronization-hub', userSynchronizationHubRoutes);
  router.use('/user-admin-console', userAdminConsoleRoutes);
  router.use('/role-definition-studio', roleDefinitionStudioRoutes);
  router.use('/permission-matrix-manager', permissionMatrixManagerRoutes);
  router.use('/role-hierarchy-builder', roleHierarchyBuilderRoutes);
  router.use('/access-control-dashboard', accessControlDashboardRoutes);
  router.use('/role-assignment-center', roleAssignmentCenterRoutes);
  router.use('/permission-audit-system', permissionAuditSystemRoutes);
  router.use('/role-template-library', roleTemplateLibraryRoutes);
  router.use('/access-review-manager', accessReviewManagerRoutes);
  router.use('/privilege-escalation-control', privilegeEscalationControlRoutes);
  router.use('/role-analytics-insights', roleAnalyticsInsightsRoutes);
  router.use('/organization-builder', organizationBuilderRoutes);
  router.use('/department-management-hub', departmentManagementHubRoutes);
  router.use('/team-formation-studio', teamFormationStudioRoutes);
  router.use('/organizational-chart-manager', organizationalChartManagerRoutes);
  router.use('/reporting-structure-designer', reportingStructureDesignerRoutes);
  router.use('/cross-functional-team-coordinator', crossFunctionalTeamCoordinatorRoutes);
  router.use('/organizational-change-manager', organizationalChangeManagerRoutes);
  router.use('/location-branch-manager', locationBranchManagerRoutes);
  router.use('/cost-center-allocation', costCenterAllocationRoutes);
  router.use('/organizational-analytics', organizationalAnalyticsRoutes);
  router.use('/user-onboarding-journey', userOnboardingJourneyRoutes);
  router.use('/user-engagement-dashboard', userEngagementDashboardRoutes);
  router.use('/user-feedback-center', userFeedbackCenterRoutes);
  router.use('/user-training-academy', userTrainingAcademyRoutes);
  router.use('/user-support-portal', userSupportPortalRoutes);
  router.use('/user-communication-hub', userCommunicationHubRoutes);
  router.use('/user-collaboration-spaces', userCollaborationSpacesRoutes);
  router.use('/user-productivity-insights', userProductivityInsightsRoutes);
  router.use('/user-wellness-dashboard', userWellnessDashboardRoutes);
  router.use('/user-recognition-system', userRecognitionSystemRoutes);
  router.use('/user-security-dashboard', userSecurityDashboardRoutes);
  router.use('/user-authentication-manager', userAuthenticationManagerRoutes);
  router.use('/user-session-monitor', userSessionMonitorRoutes);
  router.use('/user-privacy-control-center', userPrivacyControlCenterRoutes);
  router.use('/user-access-logs', userAccessLogsRoutes);
  router.use('/user-compliance-tracker', userComplianceTrackerRoutes);
  router.use('/user-risk-assessment', userRiskAssessmentRoutes);
  router.use('/user-device-management', userDeviceManagementRoutes);
  router.use('/user-data-governance', userDataGovernanceRoutes);

export { router as userManagementRoutes };
