[package]
name = "phantom-incident-response-core"
version = "1.0.1"
description = "Enterprise incident response core with comprehensive capabilities"
edition = "2021"
license = "MIT"
authors = ["Phantom Spire Security Team"]
homepage = "https://github.com/harborgrid-justin/phantom-spire"
repository = "https://github.com/harborgrid-justin/phantom-spire"
documentation = "https://docs.rs/phantom-incident-response-core"
keywords = ["cybersecurity", "phantom-spire", "security", "incident-response"]
categories = ["web-programming", "api-bindings"]

[package.metadata.napi]
name = "phantom-incident-response-core"
triples = ["x86_64-pc-windows-msvc", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[lib]
name = "phantom_incident_response_core"
crate-type = ["cdylib"]

[dependencies]
# Core NAPI dependencies - stable versions
napi = { version = "2.16", default-features = false, features = ["napi4"], optional = true }
napi-derive = { version = "2.16", default-features = false, optional = true }

# Core dependencies for incident response functionality
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"
hex = "0.4"
base64 = "0.22.1"
sha2 = "0.10"
indexmap = { version = "2.0", features = ["serde"] }
time = { version = "0.3", features = ["serde"] }

# Async runtime - standardized across platform
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Common utilities for all packages
anyhow = "1.0"
log = "0.4"
env_logger = "0.11.8"
url = "2.5"
regex = "1.10"
thiserror = "2.0.16"
bincode = "1.3"

# High-performance collections and concurrency
dashmap = "6.1.0"
parking_lot = "0.12"
rayon = "1.7"

# HTTP client - optional but standardized when needed
reqwest = { version = "0.12.23", features = ["json", "rustls-tls"], default-features = false, optional = true }

# Web framework support - optional
warp = { version = "0.4.2", optional = true }
actix-web = { version = "4.4", optional = true }

# Database backends - optional, standardized versions
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"], optional = true }
deadpool-postgres = { version = "0.14.1", optional = true }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"], optional = true }
diesel = { version = "2.1", features = ["postgres", "mysql", "sqlite", "r2d2", "chrono", "uuid"], optional = true }
diesel_migrations = { version = "2.1", optional = true }
redis = { version = "0.32.5", features = ["tokio-comp", "connection-manager"], optional = true }
mongodb = { version = "3.3.0", optional = true }
elasticsearch = { version = "8.15.0-alpha.1", optional = true }

# Monitoring and observability - optional
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }
prometheus = { version = "0.14.0", optional = true }
metrics = { version = "0.24.2", optional = true }

# Compression support - optional
flate2 = { version = "1.0", optional = true }

# Security and cryptography - optional
ring = { version = "0.17", optional = true }
rustls = { version = "0.23.31", optional = true }
jsonwebtoken = { version = "9.2", optional = true }
base64 = { version = "0.22.1", optional = true }
sha2 = { version = "0.10", optional = true }

# Enterprise standards dependency
phantom-enterprise-standards = { path = "../phantom-enterprise-standards", optional = true }


[features]
default = ["local"]
napi = ["dep:napi", "dep:napi-derive", "dep:napi-build", "napi-derive/type-def"]
local = []
reqwest = ["dep:reqwest"]

# Database backends
postgres = ["dep:tokio-postgres", "dep:deadpool-postgres", "dep:sqlx", "dep:diesel"]
redis-store = ["dep:redis"]
mongodb-store = ["dep:mongodb"]
elasticsearch-store = ["dep:elasticsearch"]
all-databases = ["postgres", "redis-store", "mongodb-store", "elasticsearch-store"]

# Enterprise monitoring and security
monitoring = ["dep:tracing", "dep:tracing-subscriber", "dep:prometheus", "dep:metrics"]
crypto = ["dep:ring", "dep:rustls", "dep:jsonwebtoken", "dep:sha2", "dep:base64"]
compression = ["dep:flate2"]

# Web and messaging
web-full = ["dep:actix-web", "dep:reqwest"]
messaging = ["redis-store"]
caching = ["redis-store"]
diesel-orm = ["dep:diesel", "dep:diesel_migrations"]
advanced-config = []

# Bundled feature sets
enterprise = ["all-databases", "messaging", "caching", "monitoring", "crypto", "phantom-enterprise-standards"]
full = ["enterprise", "web-full", "diesel-orm", "compression", "advanced-config"]

# NAPI-specific profiles for optimized Node.js builds
[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
panic = "abort"

[build-dependencies]
napi-build = { version = "=2.0.0", optional = true }
["local"]
napi = ["dep:napi", "dep:napi-derive"]
local = []
[build-dependencies]
napi-build = "2.1.0"
