# MSVC target configuration
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-cpu=native",
    "-L", "native=C:\\Users\\justi\\AppData\\Local\\node-gyp\\Cache\\22.19.0\\x64"
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[env]
NAPI_RS_FORCE_WASI = "false"
LIBPATH = "C:\\Users\\justi\\AppData\\Local\\node-gyp\\Cache\\22.19.0\\x64"
LIB = "C:\\Users\\justi\\AppData\\Local\\node-gyp\\Cache\\22.19.0\\x64"
NODE_LIB_FILE = "C:\\Users\\justi\\AppData\\Local\\node-gyp\\Cache\\22.19.0\\x64\\node.lib"