# Phantom CVE Core Configuration
# This file contains all configurable parameters to replace hardcoded values

[scoring]
# CVSS Severity thresholds
critical_threshold = 9.0
high_threshold = 7.0
medium_threshold = 4.0

# Vulnerability Scorer constants
base_exploitability_weight = 0.4
base_impact_weight = 0.6

# Attack vector bonuses
attack_vector_bonus_network = 0.3
attack_vector_bonus_adjacent = 0.2
attack_vector_bonus_local = 0.1
attack_vector_bonus_physical = 0.05

# CVSS modifiers
complexity_high_multiplier = 0.8
priv_none_bonus = 0.2
ui_required_multiplier = 0.7

# Age-based scoring
age_new_threshold_days = 30
age_old_threshold_days = 365
age_new_bonus = 0.1
age_old_multiplier = 0.9

# Impact bonuses
conf_high_bonus = 0.2
integ_high_bonus = 0.15
avail_high_bonus = 0.15

# Affected systems scoring
affected_per_product = 0.05
affected_max_bonus = 0.2

# Remediation priority calculation
base_priority_multiplier = 10.0
exploit_factor_multiplier = 50.0
max_priority_score = 100

[exploit_prediction]
# Probability constants
prob_poc = 0.70
prob_weaponization = 0.50
prob_mass_exploitation = 0.30
prob_public_exploits_given_available = 0.60
prob_in_the_wild_given_public = 0.40

# Timing constants (in days)
disclosure_lookback_days_max = 365
poc_delay_days_max = 30
weaponization_min_days = 30
weaponization_extra_days_max = 90
mass_min_days = 60
mass_extra_days_max = 180
patch_after_days = 30

# Severity-based probabilities
severity_critical_probability = 0.8
severity_high_probability = 0.6
severity_medium_probability = 0.3
severity_low_probability = 0.1
severity_none_probability = 0.05
default_probability = 0.2

# Timeline generation
risk_progression_months = 10
risk_progression_interval_days = 30
initial_exploit_likelihood = 0.1
mid_exploit_likelihood = 0.4
late_exploit_likelihood = 0.8
base_impact_magnitude = 0.5
impact_magnitude_increment = 0.05

# Zero-day and basic timeline probabilities
zero_day_probability = 0.10
basic_timeline_public_exploits_probability = 0.40

# Random number generator
rng_seed = 98765
lcg_multiplier = 1664525
lcg_increment = 1013904223

# Prediction model accuracy values
temporal_model_accuracy = 0.85
actor_model_accuracy = 0.78

# Time-based probability factors
base_time_factor = 0.3
max_time_factor = 0.7

# Risk progression increment
risk_increment_per_month = 0.1

[threat_intelligence]
# Intelligence boost weights
feed_hit_weight = 0.1
active_exploit_weight = 0.3
actor_interest_weight = 0.2

# Mock CVE generation
mock_cve_base_numbers = [10000, 20000, 30000]
mock_cve_year = 2024
max_mock_cve_counts = [5, 3, 4]

# Campaign limits
max_campaigns_per_vulnerability = 3

[actors]
opportunistic = [
    "Script Kiddies",
    "Cyber Criminal Groups",
    "Hacktivists"
]

apt = [
    "APT29",
    "APT41",
    "Lazarus Group",
    "Sandworm"
]

sophisticated = [
    "APT28",
    "APT29",
    "Equation Group",
    "FIN7"
]

[threat_feeds]
# Default feed configurations
[threat_feeds.alienvault_otx]
name = "AlienVault OTX"
reliability = 0.9
feed_type = "open_source"

[threat_feeds.abuseipdb]
name = "AbuseIPDB"
reliability = 0.8
feed_type = "reputation"

[threat_feeds.threatstream]
name = "Anomali ThreatStream"
reliability = 0.95
feed_type = "commercial"

[system_mapping]
# System identification mappings
windows_systems = "Windows Servers"
linux_systems = "Linux Servers"
apache_systems = "Web Servers"
database_systems = "Database Servers"
email_systems = "Email Servers"
network_systems = "Network Infrastructure"
default_systems = "Application Servers"
general_systems = "General Systems"

[cvss_strings]
# CVSS metric string values
high = "High"
medium = "Medium"
low = "Low"
none = "None"
required = "Required"
not_required = "Not Required"

[scoring_models]
# Default scoring models configuration
[scoring_models.temporal]
name = "temporal_scoring"
weight = 0.3
factors = ["age", "patch_availability"]

[scoring_models.environmental]
name = "environmental_scoring"
weight = 0.4
factors = ["asset_value", "exposure"]

[scoring_models.threat]
name = "threat_scoring"
weight = 0.3
factors = ["actor_interest", "exploit_maturity"]

[recommendations]
# Contextual recommendations by severity
critical = [
    "CRITICAL: Apply emergency patches immediately",
    "Implement temporary workarounds if patches unavailable",
    "Consider system isolation until patched"
]

high = [
    "Apply vendor patches within 24-48 hours",
    "Increase monitoring for exploitation attempts"
]

medium_low = [
    "Apply patches during next maintenance window",
    "Review and update security configurations"
]

general = [
    "Implement defense-in-depth measures",
    "Update threat hunting signatures",
    "Brief security team on new threat vectors"
]

[target_profile]
# Product patterns for target profile analysis
high_value_patterns = ["windows", "office", "exchange", "sharepoint"]
widespread_patterns = ["windows", "office", "apache", "nginx"]

[campaigns]
# Campaign mappings by vulnerability type
[campaigns.by_type]
rce = ["Operation Shadowhammer", "SolarWinds Campaign"]
privilege_escalation = ["DarkHalo", "UNC2452"]
information_disclosure = ["APT29 Intelligence", "Cozy Bear Data Theft"]
default = ["Generic Threat Campaign"]

zero_day = [
    "Operation Aurora",
    "Stuxnet Campaign",
    "APT Advanced Operations"
]

supply_chain = [
    "SolarWinds Orion",
    "CCleaner Supply Chain",
    "NotPetya Distribution"
]