[package]
name = "phantom-forensics-core"
version = "1.0.1"
description = "Digital forensics and incident analysis core with evidence collection and timeline reconstruction"
edition = "2021"
license = "MIT"
authors = ["Phantom Spire Security Team"]
homepage = "https://github.com/harborgrid-justin/phantom-spire"
repository = "https://github.com/harborgrid-justin/phantom-spire"
documentation = "https://docs.rs/phantom-forensics-core"
keywords = ["cybersecurity", "phantom-spire", "security", "forensics"]
categories = ["web-programming", "api-bindings"]

[package.metadata.napi]
name = "phantom-forensics-core"
triples = ["x86_64-pc-windows-msvc", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[lib]
name = "phantom_forensics_core"
crate-type = ["cdylib"]

[dependencies]
# Core NAPI dependencies - stable versions
napi = { version = "2.16", default-features = false, features = ["napi4"], optional = true }
napi-derive = { version = "2.16", default-features = false, optional = true }

# Core dependencies for forensics functionality
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"
hex = "0.4"
base64 = "0.22.1"
sha2 = "0.10"
walkdir = "2.4"
time = { version = "0.3", features = ["serde"] }

[features]
default = ["local"]
napi = ["dep:napi", "dep:napi-derive"]
local = []
[build-dependencies]
napi-build = "2.1.0"
