# Use GNU toolchain but package as MSVC
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[env]
NAPI_RS_FORCE_WASI = "false"