[toolchain]
channel = "stable"
targets = [
  "x86_64-pc-windows-msvc",
  "x86_64-pc-windows-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu"
]
profile = "default"
components = ["rustfmt", "clippy"]