[package]
name = "phantom-compliance-core"
version = "0.1.0"
description = "Compliance and regulatory framework analysis core"
edition = "2021"

[lib]
name = "phantom_compliance_core"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.0", default-features = false, features = ["napi6", "serde-json"] }
napi-derive = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"
thiserror = "1.0"

[build-dependencies]
napi-build = "2.0"
