[package]
name = "phantom-crypto-core"
version = "1.0.0"
edition = "2021"
description = "Advanced cryptographic core with secure authentication, JWT processing, and high-performance random generation"
license = "MIT"
authors = ["Phantom Spire Security"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16.0", default-features = false, features = ["napi6", "serde-json"] }
napi-derive = "2.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
tokio = { version = "1.0", features = ["full"] }
# High-performance cryptographic packages
argon2 = "0.5"
jsonwebtoken = "9.3"
rand_chacha = "0.3"
rand = "0.8"
once_cell = "1.19"
base64 = "0.22"
sha2 = "0.10"
hmac = "0.12"
aes-gcm = "0.10"
x25519-dalek = "2.0"
ed25519-dalek = "2.1"

[build-dependencies]
napi-build = "2.1.0"