[package]
name = "phantom-malware-core"
version = "1.0.1"
description = "Advanced malware analysis and threat detection core"
edition = "2021"

[lib]
name = "phantom_malware_core"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.0", default-features = false, features = ["napi6", "serde-json"] }
napi-derive = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"
thiserror = "1.0"
sha2 = "0.10"
md5 = "0.7"
base64 = "0.22"

[build-dependencies]
napi-build = "2.0"