import { Router } from 'express';

const router = Router();

import automatedbranchmanagementRoutes from './repository-automation/automated-branch-managementRoutes.js';
import repositorytemplateengineRoutes from './repository-automation/repository-template-engineRoutes.js';
import issueautoclassificationRoutes from './repository-automation/issue-auto-classificationRoutes.js';
import prreviewautomationRoutes from './repository-automation/pr-review-automationRoutes.js';
import dependencyupdatemanagerRoutes from './repository-automation/dependency-update-managerRoutes.js';
import releaseautomationhubRoutes from './repository-automation/release-automation-hubRoutes.js';
import repositoryhealthmonitorRoutes from './repository-automation/repository-health-monitorRoutes.js';
import codemigrationassistantRoutes from './repository-automation/code-migration-assistantRoutes.js';
import pipelineorchestratorRoutes from './cicd-management/pipeline-orchestratorRoutes.js';
import buildstatusdashboardRoutes from './cicd-management/build-status-dashboardRoutes.js';
import testautomationmanagerRoutes from './cicd-management/test-automation-managerRoutes.js';
import deploymentstrategyengineRoutes from './cicd-management/deployment-strategy-engineRoutes.js';
import environmentconfigurationRoutes from './cicd-management/environment-configurationRoutes.js';
import performancebenchmarkingRoutes from './cicd-management/performance-benchmarkingRoutes.js';
import rollbackmanagementRoutes from './cicd-management/rollback-managementRoutes.js';
import infrastructureascodeRoutes from './cicd-management/infrastructure-as-codeRoutes.js';
import codequalityanalyzerRoutes from './code-quality-security/code-quality-analyzerRoutes.js';
import securityscanninghubRoutes from './code-quality-security/security-scanning-hubRoutes.js';
import licensecompliancemanagerRoutes from './code-quality-security/license-compliance-managerRoutes.js';
import codecoveragetrackerRoutes from './code-quality-security/code-coverage-trackerRoutes.js';
import vulnerabilityassessmentRoutes from './code-quality-security/vulnerability-assessmentRoutes.js';
import codereviewanalyticsRoutes from './code-quality-security/code-review-analyticsRoutes.js';
import technicaldebtmonitorRoutes from './code-quality-security/technical-debt-monitorRoutes.js';
import documentationgeneratorRoutes from './code-quality-security/documentation-generatorRoutes.js';
import teamproductivityanalyticsRoutes from './collaboration-workflow/team-productivity-analyticsRoutes.js';
import projecttimelinemanagerRoutes from './collaboration-workflow/project-timeline-managerRoutes.js';
import communicationhubRoutes from './collaboration-workflow/communication-hubRoutes.js';
import knowledgebasemanagerRoutes from './collaboration-workflow/knowledge-base-managerRoutes.js';
import onboardingautomationRoutes from './collaboration-workflow/onboarding-automationRoutes.js';
import workflowtemplatesRoutes from './collaboration-workflow/workflow-templatesRoutes.js';
import integrationmanagerRoutes from './collaboration-workflow/integration-managerRoutes.js';
import reportingdashboardRoutes from './collaboration-workflow/reporting-dashboardRoutes.js';

// Mount all routes
router.use('/repository-automation/automated-branch-management', automatedbranchmanagementRoutes);
router.use('/repository-automation/repository-template-engine', repositorytemplateengineRoutes);
router.use('/repository-automation/issue-auto-classification', issueautoclassificationRoutes);
router.use('/repository-automation/pr-review-automation', prreviewautomationRoutes);
router.use('/repository-automation/dependency-update-manager', dependencyupdatemanagerRoutes);
router.use('/repository-automation/release-automation-hub', releaseautomationhubRoutes);
router.use('/repository-automation/repository-health-monitor', repositoryhealthmonitorRoutes);
router.use('/repository-automation/code-migration-assistant', codemigrationassistantRoutes);
router.use('/cicd-management/pipeline-orchestrator', pipelineorchestratorRoutes);
router.use('/cicd-management/build-status-dashboard', buildstatusdashboardRoutes);
router.use('/cicd-management/test-automation-manager', testautomationmanagerRoutes);
router.use('/cicd-management/deployment-strategy-engine', deploymentstrategyengineRoutes);
router.use('/cicd-management/environment-configuration', environmentconfigurationRoutes);
router.use('/cicd-management/performance-benchmarking', performancebenchmarkingRoutes);
router.use('/cicd-management/rollback-management', rollbackmanagementRoutes);
router.use('/cicd-management/infrastructure-as-code', infrastructureascodeRoutes);
router.use('/code-quality-security/code-quality-analyzer', codequalityanalyzerRoutes);
router.use('/code-quality-security/security-scanning-hub', securityscanninghubRoutes);
router.use('/code-quality-security/license-compliance-manager', licensecompliancemanagerRoutes);
router.use('/code-quality-security/code-coverage-tracker', codecoveragetrackerRoutes);
router.use('/code-quality-security/vulnerability-assessment', vulnerabilityassessmentRoutes);
router.use('/code-quality-security/code-review-analytics', codereviewanalyticsRoutes);
router.use('/code-quality-security/technical-debt-monitor', technicaldebtmonitorRoutes);
router.use('/code-quality-security/documentation-generator', documentationgeneratorRoutes);
router.use('/collaboration-workflow/team-productivity-analytics', teamproductivityanalyticsRoutes);
router.use('/collaboration-workflow/project-timeline-manager', projecttimelinemanagerRoutes);
router.use('/collaboration-workflow/communication-hub', communicationhubRoutes);
router.use('/collaboration-workflow/knowledge-base-manager', knowledgebasemanagerRoutes);
router.use('/collaboration-workflow/onboarding-automation', onboardingautomationRoutes);
router.use('/collaboration-workflow/workflow-templates', workflowtemplatesRoutes);
router.use('/collaboration-workflow/integration-manager', integrationmanagerRoutes);
router.use('/collaboration-workflow/reporting-dashboard', reportingdashboardRoutes);

export default router;
