[package]
name = "phantom-cve-core"
version = "0.1.0"
description = "CVE processing core with vulnerability intelligence"
edition = "2021"

[lib]
name = "phantom_cve_core"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.3.0", default-features = false, features = ["napi6", "serde-json"] }
napi-derive = "3.2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"
thiserror = "1.0"
semver = "1.0"
toml = "0.8"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
# Database dependencies
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-chrono-0_4"], optional = true }
elasticsearch = { version = "8.19.0-alpha.1", optional = true }
mongodb = { version = "2.8", optional = true }
deadpool-postgres = { version = "0.12", optional = true }

[features]
default = ["local"]
local = []
postgres = ["tokio-postgres", "deadpool-postgres"]
elasticsearch = ["dep:elasticsearch"]
mongodb = ["dep:mongodb"]
all-databases = ["postgres", "elasticsearch", "mongodb"]

[build-dependencies]
napi-build = "2.0"
