[package]
name = "phantom-cve-core"
version = "1.0.1"
description = "CVE processing core with vulnerability intelligence"
edition = "2021"

[lib]
name = "phantom_cve_core"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.3.0", default-features = false, features = ["napi6", "serde-json"] }
napi-derive = "3.2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"
thiserror = "2.0.16"
semver = "1.0"
toml = "0.9.5"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
num_cpus = "1.16"
futures-util = "0.3"
# Web frameworks
actix-web = { version = "4.4", optional = true }
rocket = { version = "0.5", features = ["json"], optional = true }
# HTTP client
reqwest = { version = "0.12.23", features = ["json", "rustls-tls"], default-features = false, optional = true }
# ORM
diesel = { version = "2.1", features = ["postgres", "mysql", "sqlite", "r2d2", "chrono", "uuid"], optional = true }
diesel_migrations = { version = "2.1", optional = true }
# Database dependencies
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-chrono-0_4"], optional = true }
elasticsearch = { version = "8.19.0-alpha.1", optional = true }
mongodb = { version = "3.3.0", optional = true }
deadpool-postgres = { version = "0.14.1", optional = true }
redis = { version = "0.32.5", features = ["aio", "tokio-comp", "connection-manager"], optional = true }
# Message queues and streaming
rdkafka = { version = "0.38.0", features = ["cmake-build"], optional = true }
lapin = { version = "3.4.0", optional = true }
# Caching and key-value stores
memcached-rs = { version = "0.5", optional = true }
# Monitoring and observability
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }
prometheus = { version = "0.14.0", optional = true }
metrics = { version = "0.24.2", optional = true }
# Security and cryptography
ring = { version = "0.17", optional = true }
rustls = { version = "0.23.31", optional = true }
jsonwebtoken = { version = "9.2", optional = true }
# Email notifications
lettre = { version = "0.11", features = ["tokio1-rustls-tls"], optional = true }
# Configuration management
config = { version = "0.15.15", features = ["yaml", "json"], optional = true }
# Rate limiting
governor = { version = "0.10.1", optional = true }
# Job queues
sidekiq = { version = "0.13.0", optional = true }

[features]
default = ["local"]
local = []
# Database features
postgres = ["tokio-postgres", "deadpool-postgres", "diesel"]
elasticsearch = ["dep:elasticsearch"]
mongodb = ["dep:mongodb"]
redis-store = ["redis"]
all-databases = ["postgres", "elasticsearch", "mongodb", "redis-store", "diesel"]
# Web framework features
actix = ["actix-web", "reqwest"]
rocket-web = ["rocket", "reqwest"]
web-full = ["actix-web", "rocket", "reqwest"]
# ORM features
diesel-orm = ["diesel", "diesel_migrations"]
# Message queue features
kafka = ["rdkafka"]
rabbitmq = ["lapin"]
messaging = ["kafka", "rabbitmq"]
# Caching features
memcached = ["memcached-rs"]
caching = ["redis-store", "memcached"]
# Monitoring and observability features
monitoring = ["tracing", "tracing-subscriber", "prometheus", "metrics"]
# Security features
crypto = ["ring", "rustls", "jsonwebtoken"]
# Notification features
notifications = ["lettre"]
# Configuration features
advanced-config = ["config"]
# Rate-limiting features
rate-limiting = ["governor"]
# Job queue features
job-queues = ["sidekiq"]
# Enterprise features
enterprise = ["all-databases", "messaging", "caching", "monitoring", "crypto", "notifications", "rate-limiting", "job-queues"]
# Complete feature set
full = ["enterprise", "web-full", "diesel-orm", "reqwest", "advanced-config"]

[build-dependencies]
napi-build = "2.0"