[package]
name = "phantom-cve-core"
version = "1.0.1"
description = "CVE processing core with vulnerability intelligence"
edition = "2021"

[lib]
name = "phantom_cve_core"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16", default-features = false, features = ["napi4"], optional = true }
napi-derive = { version = "2.16", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"], optional = true }
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"

# Enterprise standards dependency (local for now)
phantom-enterprise-standards = { path = "../phantom-enterprise-standards", optional = true }

[features]
default = ["local"]
napi = ["dep:napi", "dep:napi-derive"]
local = ["napi"]
enterprise = ["all-databases", "messaging", "caching", "monitoring", "crypto", "phantom-enterprise-standards"]
full = ["enterprise", "web-full", "diesel-orm", "advanced-config"]
web-full = ["actix-web", "rocket"]
all-databases = ["postgres", "mongodb", "redis", "elasticsearch"]
postgres = ["tokio-postgres", "deadpool-postgres", "diesel"]
mongodb = ["dep:mongodb"]
redis = ["dep:redis"]
elasticsearch = ["dep:elasticsearch"]
diesel-orm = ["diesel"]
messaging = ["rabbitmq", "kafka"]
rabbitmq = ["lapin"]
kafka = ["rdkafka"]
caching = ["redis"]
monitoring = ["prometheus", "tracing"]
prometheus = ["dep:prometheus"]
tracing = ["dep:tracing"]
crypto = ["ring", "rsa"]
ring = ["dep:ring"]
rsa = ["dep:rsa"]
actix-web = ["dep:actix-web"]
rocket = ["dep:rocket"]
advanced-config = ["config"]
config = ["dep:config"]
