[package]
name = "phantom-ml-core"
version = "1.0.1"
description = "Enterprise machine learning services for threat detection and security analytics"
edition = "2021"
license = "MIT"
authors = ["Phantom Spire Security Team"]
homepage = "https://github.com/harborgrid-justin/phantom-spire"
repository = "https://github.com/harborgrid-justin/phantom-spire"
documentation = "https://docs.rs/phantom-ml-core"
keywords = ["cybersecurity", "phantom-spire", "security", "machine-learning", "ml"]
categories = ["web-programming", "api-bindings", "science"]

[lib]
name = "phantom_ml_core"
crate-type = ["cdylib"]

[dependencies]
# Core NAPI dependencies - standardized versions
napi = { version = "3.3.0", default-features = false, features = ["napi6", "serde-json", "tokio_rt"], optional = true }
napi-derive = { version = "3.2.5", optional = true }

# Core serialization and data handling - required for all packages
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
regex = "1.10"
thiserror = "2.0.16"

# Async runtime - standardized across a platform
tokio = { version = "1.47.1", features = ["full"] }
async-trait = "0.1.89"
futures = "0.3.31"

# Common utilities for all packages
base64 = "0.22.1"
sha2 = "0.10"
url = "2.5.7"
anyhow = "1.0.99"
log = "0.4.28"
env_logger = "0.11.8"

# High-performance collections and concurrency
dashmap = "6.1.0"
parking_lot = "0.12"
rayon = "1.11.0"

# Machine learning specific dependencies
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.9.2"
statrs = "0.18.0"
polars = { version = "0.38.2", features = ["csv", "lazy"] }

# Numeric computations
num-traits = "0.2.19"
nalgebra = "0.34.0"

# HTTP client - optional but standardized when needed
reqwest = { version = "0.12.23", features = ["json", "rustls-tls"], default-features = false, optional = true }

# Web framework support - optional
warp = { version = "0.4.2", optional = true }

# Database backends - optional, standardized versions
tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"], optional = true }
bb8 = { version = "0.9.0", optional = true }
bb8-postgres = { version = "0.9.0", optional = true }
rust_decimal = { version = "1.36", features = ["tokio-pg"], optional = true }
bincode = { version = "2.0.1", optional = true }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"], optional = true }
redis = { version = "0.32.5", features = ["tokio-comp", "connection-manager"], optional = true }
mongodb = { version = "3.3.0", optional = true }
elasticsearch = { version = "9.1.0-alpha.1", optional = true }

# Diesel ORM - optional alternative to tokio-postgres
diesel = { version = "2.1", features = ["postgres", "chrono", "uuid", "serde_json"], optional = true }
diesel-async = { version = "0.6.1", features = ["postgres"], optional = true }

# Web frameworks - optional
actix-web = { version = "4.4", optional = true }
actix-cors = { version = "0.7.1", optional = true }
rocket = { version = "0.5.0", features = ["json"], optional = true }

# Monitoring and observability - optional
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }

# Compression support - optional
flate2 = { version = "1.0", optional = true }

[features]
default = ["napi", "local-storage"]

# Core features
napi = ["dep:napi", "dep:napi-derive"]
local-storage = []

# Storage backends
postgres-store = ["tokio-postgres", "bb8", "bb8-postgres", "rust_decimal", "bincode"]
redis-store = ["redis"]
mongodb-store = ["mongodb"]
elasticsearch-store = ["elasticsearch"]
all-storage = ["postgres-store", "redis-store", "mongodb-store", "elasticsearch-store"]

# Diesel ORM backend
diesel-postgres = ["diesel", "diesel-async"]

# Web features
web-server = ["warp", "reqwest"]
actix-web-server = ["actix-web", "actix-cors", "reqwest"]
rocket-server = ["rocket", "reqwest"]
web-client = ["reqwest"]

# Monitoring features
monitoring = ["tracing", "tracing-subscriber"]

# Utility features
compression = ["flate2"]

# Platform integration features
multi-tenant = []
audit-logging = ["monitoring"]
analytics = []

# Enterprise bundle
enterprise = ["all-storage", "monitoring", "compression", "multi-tenant", "audit-logging", "analytics"]

# Full feature set
full = ["enterprise", "web-server", "web-client", "actix-web-server", "rocket-server"]

[build-dependencies]
napi-build = "2.1.0"