[package]
name = "phantom-ml-core"
version = "1.0.1"
description = "Enterprise machine learning services for threat detection and security analytics"
edition = "2021"
license = "MIT"
authors = ["Phantom Spire Security Team"]
rust-version = "1.77.0"

[lib]
name = "phantom_ml_core"
crate-type = ["cdylib"]

[dependencies]
# Core NAPI dependencies for MSVC build
napi = { version = "3.3.0", default-features = false, features = ["napi6", "serde-json"] }
napi-derive = { version = "3.2.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
napi-build = "2.2.0"