[package]
name = "phantom-threatactor-core"
version = "1.0.1"
edition = "2021"
description = "Advanced threat actor intelligence and analysis core"
license = "MIT"
authors = ["Phantom Spire Team"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16.0", default-features = false, features = ["napi6", "serde-json", "tokio_rt"] }
napi-derive = "2.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.0"
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
base64 = "0.21"
sha2 = "0.10"
rand = "0.8"
async-trait = "0.1"

[build-dependencies]
napi-build = "2.1.0"