[package]
name = "phantom-threatactor-core"
version = "1.0.1"
edition = "2021"
description = "Advanced threat actor intelligence and analysis core"
license = "MIT"
authors = ["Phantom Spire Team"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16.0", default-features = false, features = ["napi6", "serde-json", "tokio_rt"], optional = true }
napi-derive = { version = "2.16.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.0"
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
base64 = "0.21"
sha2 = "0.10"
rand = "0.8"
async-trait = "0.1"

# Database backends - optional, standardized versions
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"], optional = true }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"], optional = true }
redis = { version = "0.32.5", features = ["tokio-comp", "connection-manager"], optional = true }
mongodb = { version = "3.3.0", optional = true }
elasticsearch = { version = "8.15.0-alpha.1", optional = true }
deadpool-postgres = { version = "0.14.1", optional = true }

# Web framework and ORM
actix-web = { version = "4.0", optional = true }
actix-cors = { version = "0.6", optional = true }
diesel = { version = "2.2", features = ["postgres", "chrono", "uuid", "serde_json", "r2d2"], optional = true }
diesel_migrations = { version = "2.2", optional = true }

# Additional utilities for database operations
futures = "0.3"
parking_lot = "0.12"

[features]
default = ["napi", "local-storage"]

# Core features
napi = ["dep:napi", "dep:napi-derive"]
local-storage = []

# Storage backends
postgres-store = ["tokio-postgres", "sqlx", "deadpool-postgres"]
redis-store = ["redis"]
mongodb-store = ["mongodb"]
elasticsearch-store = ["elasticsearch"]
all-storage = ["postgres-store", "redis-store", "mongodb-store", "elasticsearch-store"]

# Web and database features
web-api = ["actix-web", "actix-cors"]
diesel-orm = ["diesel", "diesel_migrations"]

# Full feature set
full = ["all-storage", "web-api", "diesel-orm"]

[build-dependencies]
napi-build = "2.1.0"
